apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookreview-frontend
  namespace: bookreview
  labels:
    app: bookreview-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bookreview-frontend
  template:
    metadata:
      labels:
        app: bookreview-frontend
    spec:
      serviceAccountName: br-sa
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "bookreview-ssm"
      containers:
      - name: bookreview-frontend
        image: 381492049685.dkr.ecr.us-east-1.amazonaws.com/frontend-repo:latest
        ports:
        - containerPort: 3000
        env:
          - name: BACKEND_URL
            value: "http://bookreview-backend-svc:3001/api/users"
        volumeMounts:
          - name: secrets-store-inline
            mountPath: "/mnt/secrets"
            readOnly: true
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
      restartPolicy: Always
